import type { RawFinaleSpeechScreen } from './finaleSpeech';
import { FINALE_SECRET } from './finaleSecret';

/**
 * Finale content kept out of sight while browsing the code: it lives base64-encoded in
 * `finaleSecret.ts`, generated by `npm run encode-finale` (see ADR 0005).
 */
export interface FinaleSecret {
  /** One expected answer per `FINALE_RIDDLE_PROMPTS` entry, same order. */
  answers: string[];
  /** One entry per screen: a plain string, or lines to reveal one by one plus an optional aside. */
  speechScreens: RawFinaleSpeechScreen[];
  closing: string;
}

/** The lines the player must complete, in order. */
export const FINALE_RIDDLE_PROMPTS: readonly string[] = [
  "Le plus important dans la vie c'est...",
  "L'important dans la vie c'est...",
  "L'important c'est...",
];

/** Shown one after the other on wrong answers, looping. Placeholder copy, to be rewritten. */
export const FINALE_WRONG_ANSWER_QUIPS: readonly string[] = [
  'Non.',
  'Toujours pas. Tu la connais pourtant, celle-là.',
  'Sérieusement ?',
  'Connecte tes deux neurones.',
  'Même Limi aurait trouvé. Et Limi ne pense à rien.',
];

export const FINALE_COPY = {
  riddleHeader: 'Complète la réplique',
  inputHint: 'Tape la suite, puis Entrée',
  rewindHint: '↑ revenir en arrière',
  closingHint: 'Appuie sur une touche pour revenir au menu',
  replayLabel: 'Relire le discours',
};

export const decodeFinaleSecret = (encoded: string = FINALE_SECRET): FinaleSecret => {
  const bytes = Uint8Array.from(atob(encoded), (char) => char.charCodeAt(0));
  return JSON.parse(new TextDecoder().decode(bytes)) as FinaleSecret;
};
