// Encodes the finale content (riddle answers, speech, closing) into src/game/finaleSecret.ts.
// Base64 only keeps the text out of sight while browsing the code: it is not encryption (ADR 0005).
// Usage: npm run encode-finale [-- path/to/source.json]   (default: finale.local.json)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const PROMPT_COUNT = 3;

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourcePath = resolve(projectRoot, process.argv[2] ?? 'finale.local.json');
const outputPath = resolve(projectRoot, 'src/game/finaleSecret.ts');

const fail = (message) => {
  console.error(`encode-finale: ${message}`);
  process.exit(1);
};

const isNonEmptyString = (value) => typeof value === 'string' && value.trim() !== '';
const isNonEmptyStringList = (value) =>
  Array.isArray(value) && value.length > 0 && value.every(isNonEmptyString);

let content;
try {
  content = JSON.parse(readFileSync(sourcePath, 'utf8'));
} catch (error) {
  fail(`cannot read ${sourcePath} (${error.message}). Copy finale.example.json to finale.local.json first.`);
}

if (!isNonEmptyStringList(content.answers) || content.answers.length !== PROMPT_COUNT) {
  fail(`"answers" must hold exactly ${PROMPT_COUNT} non-empty strings.`);
}
// A screen is either a plain string, or { lines: [...], aside?: "..." }.
const isValidScreen = (screen) => {
  if (isNonEmptyString(screen)) {
    return true;
  }
  if (typeof screen !== 'object' || screen === null || Array.isArray(screen)) {
    return false;
  }
  if (!isNonEmptyStringList(screen.lines)) {
    return false;
  }
  return screen.aside === undefined || isNonEmptyString(screen.aside);
};

if (
  !Array.isArray(content.speechScreens) ||
  content.speechScreens.length === 0 ||
  !content.speechScreens.every(isValidScreen)
) {
  fail('"speechScreens" must be a non-empty list of strings or { lines: [...], aside?: "..." } objects.');
}
if (!isNonEmptyString(content.closing)) {
  fail('"closing" must be a non-empty string.');
}

const payload = {
  answers: content.answers,
  speechScreens: content.speechScreens,
  closing: content.closing,
};
const encoded = Buffer.from(JSON.stringify(payload), 'utf8').toString('base64');
const chunks = encoded.match(/.{1,96}/g) ?? [];

writeFileSync(
  outputPath,
  [
    '// Generated by `npm run encode-finale` from finale.local.json: do not edit by hand.',
    '// Base64 hides the finale from casual reading only; it is not encryption (see ADR 0005).',
    'export const FINALE_SECRET =',
    `${chunks.map((chunk) => `  '${chunk}'`).join(' +\n')};`,
    '',
  ].join('\n'),
);

console.log(
  `encode-finale: wrote src/game/finaleSecret.ts (${payload.speechScreens.length} screens).`,
);
